In [1]:
import httpx
import requests
import brotli
import json
import time
import pandas as pd  # Ensure Pandas is installed
import sqlite3
import os
from datetime import datetime, date
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
BASE_DIR = "/home/shail/stockshortlisting"
BASE_DIR_db = "/home/shail/db"

## Growth DB

In [44]:
growdb = os.path.join(BASE_DIR_db, "growth_nse_db.db")
gr_conn = sqlite3.connect(growdb)
query_gr = f"SELECT * FROM cm_growth "
grow_df = pd.read_sql_query(query_gr, gr_conn)
grow_df.head()

         date  Trdstocks  NoTrades       Tval      Tvol     Avg
0  2026-01-05       3262  33595563  104602.45  53878.58  194.14
1  2026-01-02       3252  31153061  102438.51  57032.98  179.61
2  2026-01-01       3227  24411272   80232.39  60232.28  133.20
3  2025-12-31       3256  30669987  100695.76  76607.12  131.44
4  2025-12-30       3247  38942416  141795.39  56318.72  251.77

In [2]:
stock = 'BANKNIFTY'

In [45]:
spurdb = os.path.join(BASE_DIR_db, "fuopspur.db")
conn = sqlite3.connect(spurdb)
query_spur = f"SELECT * FROM spur WHERE symbol = '{stock}'ORDER BY Date DESC , Time DESC"
df = pd.read_sql_query(query_spur, conn)

In [53]:
spurdb = os.path.join(BASE_DIR_db, "fuopspur.db")
conn = sqlite3.connect(spurdb)
query_spur = f"SELECT * FROM spur ORDER BY Date DESC , Time DESC"
spurdf = pd.read_sql_query(query_spur, conn)

In [54]:
print (spurdf.shape)
spurdf.head()

(2269994, 13)

,symbol,latestOI,prevOI,changeInOI,avgInOI,volume,futValue,optValue,total,premValue,underlyingValue,Time,Date
0,IDFCFIRSTB,111250,57575,53675,93.23,354934,537807.52116,191346674608,596061.68424,58254.16308,70,15:32,2026-02-23
1,UPL,65759,41688,24071,57.74,235078,367891.99245,181150753677,395572.65222,27680.65977,645,15:32,2026-02-23
2,BAJAJHLDNG,11068,7068,4000,56.59,73971,29086.35531,40280428453,31024.63984,1938.28453,11495,15:32,2026-02-23
3,CUMMINSIND,43411,34066,9345,27.43,147545,190988.51098,126133003354,199686.14452,8697.63354,4880,15:32,2026-02-23
4,ICICIGI,33194,26065,7129,27.35,23544,92990.18524,5727090066,93238.40591,248.22066,1949,15:32,2026-02-23

## Getting only Bank Nifty Spur data.

In [55]:

# Assuming your DataFrame is named df
symbols_to_keep = [
    "HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK",
    "FEDERALBNK", "CANBK", "BANKBARODA", "UNIONBANK", "PNB",
    "IDFCFIRSTB", "AUBANK", "INDUSINDBK", "YESBANK"
]

filtered_df = spurdf[spurdf["symbol"].isin(symbols_to_keep)]

In [56]:
bn = filtered_df.copy()

In [57]:
print(bn.shape)
bn.head()

(145048, 13)

,symbol,latestOI,prevOI,changeInOI,avgInOI,volume,futValue,optValue,total,premValue,underlyingValue,Time,Date
0,IDFCFIRSTB,111250,57575,53675,93.23,354934,537807.52116,191346674608,596061.68424,58254.16308,70,15:32,2026-02-23
6,AUBANK,40771,32667,8104,24.81,127219,311681.61240,93690515810,324963.97050,13282.35810,976,15:32,2026-02-23
45,ICICIBANK,296774,256840,39934,15.55,232864,817069.96301,147681282889,822636.65190,5566.68889,1399,15:32,2026-02-23
55,KOTAKBANK,157815,137974,19841,14.38,100111,340540.94940,52044560820,344553.78760,4012.83820,430,15:32,2026-02-23
56,AXISBANK,192561,168363,24198,14.37,325443,444734.92162,239849283350,457007.69262,12272.77100,1385,15:32,2026-02-23

In [59]:
icici = bn[bn['symbol'] == 'ICICIBANK']
idfc = bn[bn['symbol'] == 'IDFCFIRSTB']
idfc.head()

,symbol,latestOI,prevOI,changeInOI,avgInOI,volume,futValue,optValue,total,premValue,underlyingValue,Time,Date
0,IDFCFIRSTB,111250,57575,53675,93.23,354934,537807.52116,191346674608,596061.68424,58254.16308,70,15:32,2026-02-23
212,IDFCFIRSTB,111322,57575,53747,93.35,352862,535712.09090,190126239037,593692.79452,57980.70362,70,15:30,2026-02-23
424,IDFCFIRSTB,111124,57575,53549,93.01,350458,532041.00323,188846978262,589773.07285,57732.06962,70,15:28,2026-02-23
636,IDFCFIRSTB,111193,57575,53618,93.13,349302,529725.53936,188271249146,587344.89733,57619.35796,70,15:26,2026-02-23
848,IDFCFIRSTB,111164,57575,53589,93.08,347763,527880.38849,187388585795,585268.06994,57387.68145,70,15:24,2026-02-23

In [61]:
icici.head(21)

,symbol,latestOI,prevOI,changeInOI,avgInOI,volume,futValue,optValue,total,premValue,underlyingValue,Time,Date
45,ICICIBANK,296774,256840,39934,15.55,232864,817069.96301,147681282889,822636.65190,5566.68889,1399,15:32,2026-02-23
257,ICICIBANK,296798,256840,39958,15.56,231279,813659.72975,146470407853,819196.30828,5536.57853,1398,15:30,2026-02-23
468,ICICIBANK,296561,256840,39721,15.47,230178,811311.03907,145626823006,816813.93913,5502.90006,1399,15:28,2026-02-23
681,ICICIBANK,296510,256840,39670,15.45,229167,806580.84514,145105614262,812059.70776,5478.86262,1399,15:26,2026-02-23
893,ICICIBANK,296400,256840,39560,15.40,228123,803021.93552,144438631736,808475.23288,5453.29736,1399,15:24,2026-02-23
1107,ICICIBANK,296392,256840,39552,15.40,227615,801479.89495,144090798516,806922.24011,5442.34516,1399,15:22,2026-02-23
1319,ICICIBANK,296039,256840,39199,15.26,226188,795942.46627,143241538412,801348.98039,5406.51412,1400,15:20,2026-02-23
1533,ICICIBANK,295751,256840,38911,15.15,225147,792981.30009,142507460291,798363.36300,5382.06291,1400,15:18,2026-02-23
1745,ICICIBANK,295268,256840,38428,14.96,223853,787798.10697,141753073119,793137.00816,5338.90119,1399,15:16,2026-02-23
1957,ICICIBANK,295239,256840,38399,14.95,223289,784740.45874,141501718694,790063.06568,5322.60694,1398,15:14,2026-02-23
2172,ICICIBANK,294329,256840,37489,14.60,221957,776443.76964,141019324215,781739.81179,5296.04215,1398,15:12,2026-02-23
2384,ICICIBANK,294343,256840,37503,14.60,220487,767876.10963,140427603253,773145.72216,5269.61253,1398,15:10,2026-02-23
2596,ICICIBANK,294328,256840,37488,14.60,219177,760713.11785,139860647752,765960.00537,5246.88752,1398,15:08,2026-02-23
2809,ICICIBANK,293920,256840,37080,14.44,218072,752547.82540,139589470594,757782.42134,5234.59594,1398,15:06,2026-02-23
3022,ICICIBANK,292991,256840,36151,14.08,216566,743075.09941,139057747073,748288.66014,5213.56073,1398,15:04,2026-02-23
3234,ICICIBANK,293006,256840,36166,14.08,214801,733539.38637,138273945530,738725.74167,5186.35530,1398,15:02,2026-02-23
3448,ICICIBANK,292537,256840,35697,13.90,213558,726829.98416,137722099984,732000.72400,5170.73984,1399,15:00,2026-02-23
3660,ICICIBANK,292134,256840,35294,13.74,212763,723539.81882,137270203854,728686.22736,5146.40854,1399,14:58,2026-02-23
3872,ICICIBANK,292163,256840,35323,13.75,211723,717106.49990,136890102825,722238.26815,5131.76825,1399,14:56,2026-02-23
4084,ICICIBANK,291891,256840,35051,13.65,210958,712861.26968,136560885412,717972.10380,5110.83412,1400,14:54,2026-02-23
4298,ICICIBANK,291749,256840,34909,13.59,210380,709448.74735,136330695830,714545.07565,5096.32830,1400,14:52,2026-02-23

In [5]:
idxfudb = os.path.join(BASE_DIR_db, "idxfutures.db")
idx_conn = sqlite3.connect(idxfudb)
query_idx = f"SELECT * FROM futuresIndex WHERE Stock = '{stock}'ORDER BY Date DESC , Time DESC"
idxdf = pd.read_sql_query(query_idx, idx_conn)
idxdf.head()

,Stock,Date,Time,Ltp_fu,PrChg_fu,%Prchg_fu,Tsell_fu,Tbuy_fu,Tvol_fu,Tvalue_fu,fuOI
0,BANKNIFTY,2026-02-23,15:53,61219,39.8,0.07,32250,28170,22715,41718764241,28727
1,BANKNIFTY,2026-02-23,15:32:03,61219,39.8,0.07,32250,28170,22715,41718764241,28727
2,BANKNIFTY,2026-02-23,15:30:03,61208,28.8,0.05,29550,23220,22642,41584725133.8,28727
3,BANKNIFTY,2026-02-23,15:28:03,61225.2,46,0.08,36060,33840,22495,41314728658.5,28727
4,BANKNIFTY,2026-02-23,15:26:03,61237,57.8,0.09,41220,31800,22380,41103510840,28777

## Futures and Options Live Date Processing

In [6]:

starttime = datetime.now()
print("\2\n"+ " ******************  Script run started  at ...   ", starttime)

dbpath = os.path.join(BASE_DIR_db, "fuopspur.db")
conn = sqlite3.connect(dbpath)
current_date = starttime.strftime('%Y-%m-%d')
#n50fu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
#n50op_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_opt"
#nbfu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_fut"
#nbop_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_opt"

api_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"

# Headers to mimic a real browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Accept": "application/json, text/plain, */*",
    "Referer": "https://www.nseindia.com/market-data/oi-spurts",
    "Connection": "keep-alive",
    "Accept-Encoding": "gzip, deflate, br"
	}

# Main NSE site to retrieve cookies
main_url = "https://www.nseindia.com"

# Start session with httpx
with httpx.Client() as client:
    try:
	    response = client.get(main_url, headers=headers)
	    response.raise_for_status()
	    cookies = dict(client.cookies)  # Extract cookies
	    time.sleep(3)  # Wait briefly before the next request	
	    response2 = client.get(api_url, headers=headers, cookies=cookies)
	    response2.raise_for_status()
	    data = json.loads(response2.text)
	    df = pd.json_normalize(data['data'])
	    current_time = starttime.strftime('%H:%M')
	    df['Time'] = current_time
	    df['Date'] = current_date
	    #print(df.shape)
    except httpx.HTTPStatusError as e:
        print(f"Error fetching data: {e}")
#df.to_sql('spur', conn, if_exists='append', index=False)
conn.close()
#df.to_sql('spur', conn, if_exists='append', index=False)
#bank = df[nfcolumns]
endtime = datetime.now()
elapsed = endtime - starttime

# total seconds as float
total_seconds = elapsed.total_seconds()
# minutes and seconds
minutes = int(total_seconds // 60)
seconds = int(total_seconds % 60)
milliseconds = int((total_seconds - int(total_seconds)) * 1000)
print(f"The time taken to complete the task is {minutes}:{seconds:02d}.{milliseconds:03d}")


 ******************  Script run started  at ...    2026-02-23 16:44:10.223918
The time taken to complete the task is 0:03.487

In [7]:
df.head()

,underlying,identifier,instrumentType,instrument,contract,expiryDate,optionType,strikePrice,lastPrice,change,...,closePrice,volume,totalTurnover,value,premiumTurnOver,underlyingValue,openInterest,noOfTrades,Time,Date
0,NIFTY,FUTIDXNIFTY24-02-2026XX0.00,FUTIDX,Index Futures,NIFTY 24-Feb-2026,24-Feb-2026,-,0,25700.3,115.6,...,0,8002605,2.054915e+11,2.054915e+11,2.054915e+11,25713,209503,123117,16:44,2026-02-23
1,NIFTY,FUTIDXNIFTY30-03-2026XX0.00,FUTIDX,Index Futures,NIFTY 30-Mar-2026,30-Mar-2026,-,0,25855.0,112.4,...,0,6173180,1.594704e+11,1.594704e+11,1.594704e+11,25713,151834,94972,16:44,2026-02-23
2,NIFTY,FUTIDXNIFTY28-04-2026XX0.00,FUTIDX,Index Futures,NIFTY 28-Apr-2026,28-Apr-2026,-,0,26005.1,106.0,...,0,293085,7.622232e+09,7.622232e+09,7.622232e+09,25713,10101,4509,16:44,2026-02-23

In [17]:
df.columns

Index(['underlying', 'identifier', 'instrumentType', 'instrument', 'contract',
       'expiryDate', 'optionType', 'strikePrice', 'lastPrice', 'change',
       'pChange', 'openPrice', 'highPrice', 'lowPrice', 'closePrice', 'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date'],
      dtype='object')

In [22]:
reqcol = ['underlying', 'instrumentType', 'contract',
       'lastPrice', 'change',
       'pChange','highPrice', 'lowPrice',  'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date']
df = df[reqcol]

In [23]:
df.head()

,underlying,instrumentType,contract,lastPrice,change,pChange,highPrice,lowPrice,volume,totalTurnover,value,premiumTurnOver,underlyingValue,openInterest,noOfTrades,Time,Date
0,NIFTY,FUTIDX,NIFTY 24-Feb-2026,25700.3,115.6,0.45,25779.9,25593.3,8002605,2.054915e+11,2.054915e+11,2.054915e+11,25713,209503,123117,16:00,2026-02-23
1,NIFTY,FUTIDX,NIFTY 30-Mar-2026,25855.0,112.4,0.44,25934.6,25758.5,6173180,1.594704e+11,1.594704e+11,1.594704e+11,25713,151834,94972,16:00,2026-02-23
2,NIFTY,FUTIDX,NIFTY 28-Apr-2026,26005.1,106.0,0.41,26078.0,25925.0,293085,7.622232e+09,7.622232e+09,7.622232e+09,25713,10101,4509,16:00,2026-02-23

## Using request instead of client.

In [39]:

starttime = datetime.now()
print("\2\n"+ " ******************  Script run started  at ...   ", starttime)
current_date = starttime.strftime('%Y-%m-%d')
main_url = 'https://www.nseindia.com'
#fno_url = f'https://www.nseindia.com/api/NextApi/apiClient/GetQuoteApi?functionName=getSymbolDerivativesData&symbol={encoded_stock}'
fno_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/91.0.4472.124 Safari/537.36',
    'Referer': main_url,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5'
}
session = requests.Session()
retry = Retry(
    total=2,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"]
)
adapter = HTTPAdapter(max_retries=retry)
session.mount("https://", adapter)
session.mount("http://", adapter)
try:
    session.get(main_url, headers=headers)
    time.sleep(1)
    response2 = session.get(fno_url, headers=headers)
    response2.raise_for_status()
    fno = response2.json()
    df = pd.json_normalize(fno['data'])
    current_time = starttime.strftime('%H:%M')
    # These lines below were likely causing the TabError
    df['Time'] = current_time
    df['Date'] = current_date
    df['date'], df['Dtime'] = fno['timestamp'].split()
except requests.exceptions.RequestException as e:
    print(f"An error occurred for : {e}")

#df.to_sql('spur', conn, if_exists='append', index=False)
#bank = df[nfcolumns]
endtime = datetime.now()
elapsed = endtime - starttime

# total seconds as float
total_seconds = elapsed.total_seconds()
# minutes and seconds
minutes = int(total_seconds // 60)
seconds = int(total_seconds % 60)
milliseconds = int((total_seconds - int(total_seconds)) * 1000)
print(f"The time taken to complete the task is {minutes}:{seconds:02d}.{milliseconds:03d}")


 ******************  Script run started  at ...    2026-02-23 16:20:09.959504
The time taken to complete the task is 0:01.229

In [37]:
reqcol = ['underlying', 'instrumentType', 'contract',
       'lastPrice', 'change',
       'pChange','highPrice', 'lowPrice',  'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date']
df = df[reqcol]
df.head()

,underlying,instrumentType,contract,lastPrice,change,pChange,highPrice,lowPrice,volume,totalTurnover,value,premiumTurnOver,underlyingValue,openInterest,noOfTrades,Time,Date
0,NIFTY,FUTIDX,NIFTY 24-Feb-2026,25700.3,115.6,0.45,25779.9,25593.3,8002605,2.054915e+11,2.054915e+11,2.054915e+11,25713,209503,123117,16:19,2026-02-23
1,NIFTY,FUTIDX,NIFTY 30-Mar-2026,25855.0,112.4,0.44,25934.6,25758.5,6173180,1.594704e+11,1.594704e+11,1.594704e+11,25713,151834,94972,16:19,2026-02-23
2,NIFTY,FUTIDX,NIFTY 28-Apr-2026,26005.1,106.0,0.41,26078.0,25925.0,293085,7.622232e+09,7.622232e+09,7.622232e+09,25713,10101,4509,16:19,2026-02-23

## Bank Nifty Futures Live data.

In [69]:
starttime = datetime.now()
print("\2\n"+ " ******************  Script run started  at ...   ", starttime)
current_date = starttime.strftime('%Y-%m-%d')
main_url = 'https://www.nseindia.com'
#fno_url = f'https://www.nseindia.com/api/NextApi/apiClient/GetQuoteApi?functionName=getSymbolDerivativesData&symbol={encoded_stock}'
#fno_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
nbfu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_fut"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/91.0.4472.124 Safari/537.36',
    'Referer': main_url,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5'
}
session = requests.Session()
retry = Retry(
    total=2,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"]
)
adapter = HTTPAdapter(max_retries=retry)
session.mount("https://", adapter)
session.mount("http://", adapter)
try:
    session.get(main_url, headers=headers)
    time.sleep(1)
    response2 = session.get(nbfu_url, headers=headers)
    response2.raise_for_status()
    fno = response2.json()
    df = pd.json_normalize(fno['data'])
    current_time = starttime.strftime('%H:%M')
    # These lines below were likely causing the TabError
    df['Time'] = current_time
    df['Date'] = current_date


except requests.exceptions.RequestException as e:
    print(f"An error occurred for : {e}")

#df.to_sql('spur', conn, if_exists='append', index=False)
#bank = df[nfcolumns]
reqcol = ['underlying', 'instrumentType', 'contract',
       'lastPrice', 'change',
       'pChange','highPrice', 'lowPrice',  'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date']
df = df[reqcol]
endtime = datetime.now()
elapsed = endtime - starttime

# total seconds as float
total_seconds = elapsed.total_seconds()
# minutes and seconds
minutes = int(total_seconds // 60)
seconds = int(total_seconds % 60)
milliseconds = int((total_seconds - int(total_seconds)) * 1000)
print(f"The time taken to complete the task is {minutes}:{seconds:02d}.{milliseconds:03d}")


 ******************  Script run started  at ...    2026-02-23 16:39:02.336545
The time taken to complete the task is 0:01.351

In [70]:
df.head()

,underlying,instrumentType,contract,lastPrice,change,pChange,highPrice,lowPrice,volume,totalTurnover,value,premiumTurnOver,underlyingValue,openInterest,noOfTrades,Time,Date
0,BANKNIFTY,FUTIDX,BANKNIFTY 24-Feb-2026,61219.0,39.8,0.07,61500.0,61020.2,681450,4.171876e+10,4.171876e+10,4.171876e+10,61264.25,28727,22715,16:39,2026-02-23
1,BANKNIFTY,FUTIDX,BANKNIFTY 30-Mar-2026,61603.4,57.6,0.09,61850.0,61416.0,635610,3.915076e+10,3.915076e+10,3.915076e+10,61264.25,37365,21187,16:39,2026-02-23
2,BANKNIFTY,FUTIDX,BANKNIFTY 28-Apr-2026,61940.0,73.2,0.12,62175.8,61764.0,28080,1.739593e+09,1.739593e+09,1.739593e+09,61264.25,3077,936,16:39,2026-02-23

## Bank Nifty Options Live Data.

In [54]:
starttime = datetime.now()
print("\2\n"+ " ******************  Script run started  at ...   ", starttime)
current_date = starttime.strftime('%Y-%m-%d')
main_url = 'https://www.nseindia.com'
#n50fu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
#n50op_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_opt"
#nbfu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_fut"
nbop_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_opt"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/91.0.4472.124 Safari/537.36',
    'Referer': main_url,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5'
}
session = requests.Session()
retry = Retry(
    total=2,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"]
)
adapter = HTTPAdapter(max_retries=retry)
session.mount("https://", adapter)
session.mount("http://", adapter)
try:
    session.get(main_url, headers=headers)
    time.sleep(1)
    response2 = session.get(nbop_url, headers=headers)
    response2.raise_for_status()
    fno = response2.json()
    df = pd.json_normalize(fno['data'])
    current_time = starttime.strftime('%H:%M')
    # These lines below were likely causing the TabError
    df['Time'] = current_time
    df['Date'] = current_date


except requests.exceptions.RequestException as e:
    print(f"An error occurred for : {e}")

#df.to_sql('spur', conn, if_exists='append', index=False)
#bank = df[nfcolumns]
opcol = ['underlying', 'instrumentType', 'contract',
       'optionType', 'strikePrice', 'lastPrice', 'change',
       'pChange','highPrice', 'lowPrice', 'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date']
df = df[opcol]
endtime = datetime.now()
elapsed = endtime - starttime

# total seconds as float
total_seconds = elapsed.total_seconds()
# minutes and seconds
minutes = int(total_seconds // 60)
seconds = int(total_seconds % 60)
milliseconds = int((total_seconds - int(total_seconds)) * 1000)
print(f"The time taken to complete the task is {minutes}:{seconds:02d}.{milliseconds:03d}")


 ******************  Script run started  at ...    2026-02-23 16:29:54.820149
The time taken to complete the task is 0:01.250

In [55]:
df.head()

,underlying,instrumentType,contract,optionType,strikePrice,lastPrice,change,pChange,highPrice,lowPrice,volume,totalTurnover,value,premiumTurnOver,underlyingValue,openInterest,noOfTrades,Time,Date
0,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Put,61000,134.95,-102.85,-43.25,260.00,105.90,37859100,6.980839e+09,6.980839e+09,2.316386e+12,61264.25,42251.0,1261970,16:29,2026-02-23
1,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Call,61300,175.35,-79.15,-31.10,379.90,128.95,27244950,6.086794e+09,6.086794e+09,1.676202e+12,61264.25,26395.0,908165,16:29,2026-02-23
2,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Call,61200,225.00,-75.85,-25.21,447.45,164.40,26960400,7.018331e+09,7.018331e+09,1.656995e+12,61264.25,22479.0,898680,16:29,2026-02-23
3,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Call,61500,103.00,-67.55,-39.61,268.15,78.15,26895870,3.882688e+09,3.882688e+09,1.657979e+12,61264.25,34797.0,896529,16:29,2026-02-23
4,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Put,61200,213.20,-106.35,-33.28,367.10,152.00,26153250,6.898443e+09,6.898443e+09,1.607477e+12,61264.25,15870.0,871775,16:29,2026-02-23

In [52]:
df.columns

Index(['underlying', 'identifier', 'instrumentType', 'instrument', 'contract',
       'expiryDate', 'optionType', 'strikePrice', 'lastPrice', 'change',
       'pChange', 'openPrice', 'highPrice', 'lowPrice', 'closePrice', 'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date'],
      dtype='object')

In [ ]:
opcol = ['underlying', 'instrumentType' 'contract',
       'optionType', 'strikePrice', 'lastPrice', 'change',
       'pChange','highPrice', 'lowPrice', 'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date']

In [71]:
starttime = datetime.now()
print("\2\n"+ " ******************  Script run started  at ...   ", starttime)
current_date = starttime.strftime('%Y-%m-%d')
main_url = 'https://www.nseindia.com'
#n50fu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
#n50op_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_opt"
#nbfu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_fut"
nbop_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_opt"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/91.0.4472.124 Safari/537.36',
    'Referer': main_url,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5'
}
session = requests.Session()
retry = Retry(
    total=2,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"]
)
adapter = HTTPAdapter(max_retries=retry)
session.mount("https://", adapter)
session.mount("http://", adapter)
try:
    session.get(main_url, headers=headers)
    time.sleep(1)
    response2 = session.get(nbop_url, headers=headers)
    response2.raise_for_status()
    fno = response2.json()
    df = pd.json_normalize(fno['data'])
    df['Date'], df['Time'] = fno['timestamp'].split()

except requests.exceptions.RequestException as e:
    print(f"An error occurred for : {e}")

#df.to_sql('spur', conn, if_exists='append', index=False)
#bank = df[nfcolumns]
opcol = ['underlying', 'instrumentType', 'contract',
       'optionType', 'strikePrice', 'lastPrice', 'change',
       'pChange','highPrice', 'lowPrice', 'volume',
       'totalTurnover', 'value', 'premiumTurnOver', 'underlyingValue',
       'openInterest', 'noOfTrades', 'Time', 'Date']
df = df[opcol]
endtime = datetime.now()
elapsed = endtime - starttime

# total seconds as float
total_seconds = elapsed.total_seconds()
# minutes and seconds
minutes = int(total_seconds // 60)
seconds = int(total_seconds % 60)
milliseconds = int((total_seconds - int(total_seconds)) * 1000)
print(f"The time taken to complete the task is {minutes}:{seconds:02d}.{milliseconds:03d}")


 ******************  Script run started  at ...    2026-02-23 16:40:51.887317
The time taken to complete the task is 0:01.390

In [72]:
df.head()

,underlying,instrumentType,contract,optionType,strikePrice,lastPrice,change,pChange,highPrice,lowPrice,volume,totalTurnover,value,premiumTurnOver,underlyingValue,openInterest,noOfTrades,Time,Date
0,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Put,61000,134.95,-102.85,-43.25,260.00,105.90,37859100,6.980839e+09,6.980839e+09,2.316386e+12,61264.25,42251.0,1261970,15:30:00,23-Feb-2026
1,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Call,61300,175.35,-79.15,-31.10,379.90,128.95,27244950,6.086794e+09,6.086794e+09,1.676202e+12,61264.25,26395.0,908165,15:30:00,23-Feb-2026
2,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Call,61200,225.00,-75.85,-25.21,447.45,164.40,26960400,7.018331e+09,7.018331e+09,1.656995e+12,61264.25,22479.0,898680,15:30:00,23-Feb-2026
3,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Call,61500,103.00,-67.55,-39.61,268.15,78.15,26895870,3.882688e+09,3.882688e+09,1.657979e+12,61264.25,34797.0,896529,15:30:00,23-Feb-2026
4,BANKNIFTY,OPTIDX,BANKNIFTY 24-Feb-2026,Put,61200,213.20,-106.35,-33.28,367.10,152.00,26153250,6.898443e+09,6.898443e+09,1.607477e+12,61264.25,15870.0,871775,15:30:00,23-Feb-2026

In [73]:
df.shape

(894, 19)

## OI Spurts Underlying and Contracts
### https://www.nseindia.com/api/live-analysis-oi-spurts-underlyings
### https://www.nseindia.com/api/live-analysis-oi-spurts-contracts

In [13]:
main_url = 'https://www.nseindia.com'
#n50fu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
#n50op_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_opt"
#nbfu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_fut"
#oispurts_url = "https://www.nseindia.com/api/live-analysis-oi-spurts-underlyings"
#oisprcon_url = "https://www.nseindia.com/api/live-analysis-oi-spurts-contracts"
oispurts_url = "https://www.nseindia.com/api/live-analysis-oi-spurts-underlyings"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/91.0.4472.124 Safari/537.36',
    'Referer': main_url,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5'
}
session = requests.Session()
retry = Retry(
    total=2,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"]
)
adapter = HTTPAdapter(max_retries=retry)
session.mount("https://", adapter)
session.mount("http://", adapter)
try:
    session.get(main_url, headers=headers)
    time.sleep(1)
    response2 = session.get(oispurts_url, headers=headers)
    response2.raise_for_status()
    fno = response2.json()
    df = pd.json_normalize(fno['data'])
    df['Date'], df['Time'] = fno['timestamp'].split()

except requests.exceptions.RequestException as e:
    print(f"An error occurred for : {e}")
df.head()

,symbol,latestOI,prevOI,changeInOI,avgInOI,volume,futValue,optValue,total,premValue,underlyingValue,Date,Time
0,IDFCFIRSTB,111250,57575,53675,93.23,354934,537807.52116,191346674608,596061.68424,58254.16308,70,23-Feb-2026,15:31:39
1,UPL,65759,41688,24071,57.74,235078,367891.99245,181150753677,395572.65222,27680.65977,645,23-Feb-2026,15:31:39
2,BAJAJHLDNG,11068,7068,4000,56.59,73971,29086.35531,40280428453,31024.63984,1938.28453,11495,23-Feb-2026,15:31:39
3,CUMMINSIND,43411,34066,9345,27.43,147545,190988.51098,126133003354,199686.14452,8697.63354,4880,23-Feb-2026,15:31:39
4,ICICIGI,33194,26065,7129,27.35,23544,92990.18524,5727090066,93238.40591,248.22066,1949,23-Feb-2026,15:31:39

## Spurts Contracts.

In [14]:
main_url = 'https://www.nseindia.com'
#n50fu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_fut"
#n50op_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nse50_opt"
#nbfu_url = "https://www.nseindia.com/api/liveEquity-derivatives?index=nifty_bank_fut"
#oispurts_url = "https://www.nseindia.com/api/live-analysis-oi-spurts-underlyings"
#oisprcon_url = "https://www.nseindia.com/api/live-analysis-oi-spurts-contracts"
oisprcon_url = "https://www.nseindia.com/api/live-analysis-oi-spurts-contracts"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                  'Chrome/91.0.4472.124 Safari/537.36',
    'Referer': main_url,
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5'
}
session = requests.Session()
retry = Retry(
    total=2,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"]
)
adapter = HTTPAdapter(max_retries=retry)
session.mount("https://", adapter)
session.mount("http://", adapter)
try:
    session.get(main_url, headers=headers)
    time.sleep(1)
    response2 = session.get(oisprcon_url, headers=headers)
    response2.raise_for_status()
    fno = response2.json()
    df = pd.json_normalize(fno['data'])
    df['Date'], df['Time'] = fno['timestamp'].split()

except requests.exceptions.RequestException as e:
    print(f"An error occurred for : {e}")
df.head()

,Slide-in-OI-Slide,Slide-in-OI-Rise,Rise-in-OI-Rise,Rise-in-OI-Slide,Date,Time
0,"[{'type': 'SS', 'symbol': 'NIFTY', 'instrument...",NaN,NaN,NaN,23-Feb-2026,15:31:39
1,NaN,"[{'type': 'SR', 'symbol': 'NIFTY', 'instrument...",NaN,NaN,23-Feb-2026,15:31:39
2,NaN,NaN,"[{'type': 'RR', 'symbol': 'HDFCBANK', 'instrum...",NaN,23-Feb-2026,15:31:39
3,NaN,NaN,NaN,"[{'type': 'RS', 'symbol': 'NIFTY', 'instrument...",23-Feb-2026,15:31:39

In [25]:
dfdata = pd.json_normalize(fno['data'][0]['Slide-in-OI-Slide'])
dfdata.head()

,type,symbol,instrument,expiryDate,optionType,strikePrice,ltp,prevClose,pChange,latestOI,prevOI,changeInOI,volume,turnover,premTurnover,underlyingValue,identifier,instrumentType,pChangeInOI
0,SS,NIFTY,Index Options,24-Feb-2026,Call,27000,1.00,1.50,-33.33,187616,243925,-56309,1041659,866.66028,866.66028,25713.0,OPTIDXNIFTY24-02-2026CE27000,OPTIDX,-23.08
1,SS,NIFTY,Index Options,24-Feb-2026,Put,24800,6.05,17.05,-64.52,69651,116021,-46370,836820,3383.26326,3383.26326,25713.0,OPTIDXNIFTY24-02-2026PE24800,OPTIDX,-39.97
2,SS,NIFTY,Index Options,24-Feb-2026,Call,27300,0.95,1.15,-17.39,28335,56821,-28486,178458,126.43749,126.43749,25713.0,OPTIDXNIFTY24-02-2026CE27300,OPTIDX,-50.13
3,SS,NIFTY,Index Options,24-Feb-2026,Call,27500,0.75,1.05,-28.57,57251,82720,-25469,210023,128.32405,128.32405,25713.0,OPTIDXNIFTY24-02-2026CE27500,OPTIDX,-30.79
4,SS,NIFTY,Index Options,24-Feb-2026,Call,26550,1.55,2.70,-42.59,15972,34856,-18884,562644,760.69468,760.69468,25713.0,OPTIDXNIFTY24-02-2026CE26550,OPTIDX,-54.18

In [39]:
df2 = pd.json_normalize(fno['data'][1]['Slide-in-OI-Rise'])
df3 = pd.json_normalize(fno['data'][2]['Rise-in-OI-Rise'])
df4 = pd.json_normalize(fno['data'][3]['Rise-in-OI-Slide'])
df2.head()

,type,symbol,instrument,expiryDate,optionType,strikePrice,ltp,prevClose,pChange,latestOI,prevOI,changeInOI,volume,turnover,premTurnover,underlyingValue,identifier,instrumentType,pChangeInOI
0,SR,NIFTY,Index Options,24-Feb-2026,Call,25600,144.5,119.35,21.07,73481,118035,-44554,4232600,392512.27730,392512.27730,25713.0,OPTIDXNIFTY24-02-2026CE25600,OPTIDX,-37.75
1,SR,NIFTY,Index Options,24-Feb-2026,Call,25500,224.6,179.25,25.30,58088,82816,-24728,1279710,182158.40038,182158.40038,25713.0,OPTIDXNIFTY24-02-2026CE25500,OPTIDX,-29.86
2,SR,NIFTY,Index Options,24-Feb-2026,Call,25550,184.5,145.30,26.98,18066,35385,-17319,990952,114047.67472,114047.67472,25713.0,OPTIDXNIFTY24-02-2026CE25550,OPTIDX,-48.94
3,SR,NIFTY,Index Options,24-Feb-2026,Call,25400,317.0,255.00,24.31,15772,23678,-7906,213319,42092.21173,42092.21173,25713.0,OPTIDXNIFTY24-02-2026CE25400,OPTIDX,-33.39
4,SR,BAJAJ-AUTO,Stock Futures,24-Feb-2026,-,0,9885.5,9813.50,0.73,6846,12697,-5851,12223,90422.45379,90422.45379,9884.5,FUTSTKBAJAJ-AUTO24-02-2026XX0,FUTSTK,-46.08

In [40]:
df3.head()

,type,symbol,instrument,expiryDate,optionType,strikePrice,ltp,prevClose,pChange,latestOI,prevOI,changeInOI,volume,turnover,premTurnover,underlyingValue,identifier,instrumentType,pChangeInOI
0,RR,HDFCBANK,Stock Futures,30-Mar-2026,-,0,930.40,919.65,1.17,441057,345913,95144,118352,6.042183e+05,6.042183e+05,924.1,FUTSTKHDFCBANK30-03-2026XX0,FUTSTK,27.51
1,RR,NIFTY,Index Options,24-Feb-2026,Call,25750,59.55,57.20,4.11,152974,72289,80685,7473606,3.419922e+05,3.419922e+05,25713.0,OPTIDXNIFTY24-02-2026CE25750,OPTIDX,111.61
2,RR,NIFTY,Index Futures,30-Mar-2026,-,0,25855.00,25742.60,0.44,151834,86332,65502,94972,1.594704e+06,1.594704e+06,25713.0,FUTIDXNIFTY30-03-2026XX0,FUTIDX,75.87
3,RR,NIFTY,Index Options,24-Feb-2026,Call,25700,81.65,74.85,9.08,197150,136461,60689,11807537,6.771563e+05,6.771563e+05,25713.0,OPTIDXNIFTY24-02-2026CE25700,OPTIDX,44.47
4,RR,RELIANCE,Stock Futures,30-Mar-2026,-,0,1433.00,1429.60,0.24,177655,127804,49851,58464,4.186841e+05,4.186841e+05,1425.0,FUTSTKRELIANCE30-03-2026XX0,FUTSTK,39.01

In [41]:
df4.head()

,type,symbol,instrument,expiryDate,optionType,strikePrice,ltp,prevClose,pChange,latestOI,prevOI,changeInOI,volume,turnover,premTurnover,underlyingValue,identifier,instrumentType,pChangeInOI
0,RS,NIFTY,Index Options,24-Feb-2026,Put,25700,82.00,181.30,-54.77,171117,49925,121192,9877558,662714.99889,662714.99889,25713.0,OPTIDXNIFTY24-02-2026PE25700,OPTIDX,242.75
1,RS,NIFTY,Index Options,24-Feb-2026,Put,25600,47.10,128.80,-63.43,173084,98538,74546,9367333,402163.02402,402163.02402,25713.0,OPTIDXNIFTY24-02-2026PE25600,OPTIDX,75.65
2,RS,NIFTY,Index Options,24-Feb-2026,Call,26000,9.00,16.00,-43.75,285253,217495,67758,4775022,43483.73784,43483.73784,25713.0,OPTIDXNIFTY24-02-2026CE26000,OPTIDX,31.15
3,RS,NIFTY,Index Options,24-Feb-2026,Put,25650,62.15,149.75,-58.50,96826,36187,60639,8302078,458905.66352,458905.66352,25713.0,OPTIDXNIFTY24-02-2026PE25650,OPTIDX,167.57
4,RS,NIFTY,Index Options,24-Feb-2026,Call,25800,41.65,43.30,-3.81,225726,165418,60308,8720038,290939.70785,290939.70785,25713.0,OPTIDXNIFTY24-02-2026CE25800,OPTIDX,36.46

In [42]:
df4['instrumentType'].unique()

array(['OPTIDX', 'FUTSTK'], dtype=object)

## Indices Change code.

In [62]:
spurdb = os.path.join(BASE_DIR_db, "fuopspur.db")
conn = sqlite3.connect(spurdb)
query_spur = f"SELECT * FROM spur ORDER BY Date DESC , Time DESC"
spurdf = pd.read_sql_query(query_spur, conn)

# Assuming your DataFrame is named df
banknifty = [
    "HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK",
    "FEDERALBNK", "CANBK", "BANKBARODA", "UNIONBANK", "PNB",
    "IDFCFIRSTB", "AUBANK", "INDUSINDBK", "YESBANK"
]

bn_df = spurdf[spurdf["symbol"].isin(banknifty)]

In [67]:
icici = bn[bn['symbol'] == 'ICICIBANK']
idfc = bn[bn['symbol'] == 'IDFCFIRSTB']
idfc.head()

,symbol,latestOI,prevOI,changeInOI,avgInOI,volume,futValue,optValue,total,premValue,underlyingValue,Time,Date
0,IDFCFIRSTB,111250,57575,53675,93.23,354934,537807.52116,191346674608,596061.68424,58254.16308,70,15:32,2026-02-23
212,IDFCFIRSTB,111322,57575,53747,93.35,352862,535712.09090,190126239037,593692.79452,57980.70362,70,15:30,2026-02-23
424,IDFCFIRSTB,111124,57575,53549,93.01,350458,532041.00323,188846978262,589773.07285,57732.06962,70,15:28,2026-02-23
636,IDFCFIRSTB,111193,57575,53618,93.13,349302,529725.53936,188271249146,587344.89733,57619.35796,70,15:26,2026-02-23
848,IDFCFIRSTB,111164,57575,53589,93.08,347763,527880.38849,187388585795,585268.06994,57387.68145,70,15:24,2026-02-23

In [68]:
idfc.columns

Index(['symbol', 'latestOI', 'prevOI', 'changeInOI', 'avgInOI', 'volume',
       'futValue', 'optValue', 'total', 'premValue', 'underlyingValue', 'Time',
       'Date'],
      dtype='object')

In [71]:
reqcol = ['symbol','Date','Time', 'latestOI','volume',
       'futValue', 'optValue', 'total', 'premValue', 'underlyingValue']
icici = icici[reqcol]    
icici.head()

,symbol,Date,Time,latestOI,volume,futValue,optValue,total,premValue,underlyingValue
45,ICICIBANK,2026-02-23,15:32,296774,232864,817069.96301,147681282889,822636.65190,5566.68889,1399
257,ICICIBANK,2026-02-23,15:30,296798,231279,813659.72975,146470407853,819196.30828,5536.57853,1398
468,ICICIBANK,2026-02-23,15:28,296561,230178,811311.03907,145626823006,816813.93913,5502.90006,1399
681,ICICIBANK,2026-02-23,15:26,296510,229167,806580.84514,145105614262,812059.70776,5478.86262,1399
893,ICICIBANK,2026-02-23,15:24,296400,228123,803021.93552,144438631736,808475.23288,5453.29736,1399

In [ ]:
changecol = ['latestOI','volume',
       'futValue', 'optValue', 'total', 'premValue', 'underlyingValue']

In [ ]:
import pandas as pd
import streamlit as st
import sqlite3
from datetime import date
import altair as alt
import numpy as np
import os

# -----------------------------
# Config
# -----------------------------
BASE_DIR_db = "/home/shail/db"
TODAY = date.today()

# -----------------------------
# Utility Functions
# -----------------------------
def safe_numeric(df, cols):
    for col in cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    return df

def diffprocess(df):
    df = safe_numeric(df.copy(), ['Tval','Tvol','noOfTrades','noOfOrders'])
    df.fillna(0, inplace=True)

    if 'Tval' in df.columns:
        df['Valchg'] = df['Tval'].diff(-1).round(2)
        df['Valchg%'] = (df['Tval'].diff(-1)*100/df['Tval'].shift(-1).replace(0,np.nan)).round(2)
    if 'Tvol' in df.columns:
        df['Volchg'] = df['Tvol'].diff(-1).round(2)
        df['Volchg%'] = (df['Tvol'].diff(-1)*100/df['Tvol'].shift(-1).replace(0,np.nan)).round(2)
    if {'Valchg','Volchg'}.issubset(df.columns):
        df['Chgavg'] = (df['Valchg']*100/df['Volchg']).round(2)
        df['Tavgchg%'] = (df['Chgavg'].diff(-1)*100/df['Chgavg'].shift(-1).replace(0,np.nan)).round(2)

    if 'noOfOrders' in df.columns:
        df['Orderchg_lac'] = (df['noOfOrders'].diff(-1)/100000).round(3)
        df['Orderchg%'] = (df['noOfOrders'].diff(-1)*100/df['noOfOrders'].shift(-1).replace(0,np.nan)).round(2)
    if 'noOfTrades' in df.columns:
        df['Trdnochg'] = df['noOfTrades'].diff(-1).round(2)
        df['Trdnochg%'] = (df['noOfTrades'].diff(-1)*100/df['noOfTrades'].shift(-1).replace(0,np.nan)).round(2)

    if {'Valchg%','Volchg%'}.issubset(df.columns):
        df['Var%'] = (df['Valchg%']-df['Volchg%']).round(2)
    if {'Tval','Tvol'}.issubset(df.columns):
        df['Totavg'] = (df['Tval']*100/df['Tvol']).round(2)

    df.fillna(0, inplace=True)
    return df

def valuechange(df):
    df = df.copy()
    df.rename(columns={
        'declines':'Dec','advances':'Adv','unchanged':'Unchg',
        'dayHigh':'High','dayLow':'Low','lastPrice':'LTP',
        'pChange':'pchg','change':'chg',
        'totalTradedVolume':'Tvol','totalTradedValue':'Tval'
    }, inplace=True)

    df['ffmc'] = (df.get('ffmc',0)/10000000).round(3)
    df['Valchg'] = (df['Tval'].diff(-1)/10000000).round(2)
    df['Volchg'] = (df['Tvol'].diff(-1)/100000).round(2)
    df['Chgavg'] = (df['Valchg']*100/df['Volchg']).round(2)
    df['Tavgchg%'] = (df['Chgavg'].diff(-1)*100/df['Chgavg'].shift(-1).replace(0,pd.NA)).round(2)
    df['Valchg%'] = (df['Tval'].diff(-1)*100/df['Tval'].shift(-1).replace(0,pd.NA)).round(2)
    df['Volchg%'] = (df['Tvol'].diff(-1)*100/df['Tvol'].shift(-1).replace(0,pd.NA)).round(2)
    df['Var%'] = (df['Valchg%']-df['Volchg%']).round(2)
    df['rto%'] = (df['Valchg%']/df['Volchg%']).round(2)
    df['Totavg'] = (df['Tval']/df['Tvol']).round(2)
    df['Tval'] = (df['Tval']/10000000).round(3)
    df.fillna(0, inplace=True)

    keep = ['symbol','Date','Time','pchg','Valchg','Volchg','Valchg%','Volchg%',
            'Var%','High','Low','LTP','chg','Adv','Dec','Unchg',
            'Tvol','Tval','Chgavg','rto%','Totavg']
    return df[[c for c in keep if c in df.columns]]

def load_sql(db_path, table, query):
    with sqlite3.connect(db_path) as conn:
        return pd.read_sql_query(query, conn)

def parse_time(df, fmt):
    if 'Time' in df.columns:
        df['Time'] = pd.to_datetime(df['Time'], format=fmt, errors="coerce")
        df.sort_values(by='Time', inplace=True)
        df.reset_index(drop=True, inplace=True)
    return df

def plot_charts(df, label, chart_specs):
    for col, color, title in chart_specs:
        if col in df.columns:
            chart = (
                alt.Chart(df)
                .mark_line(point=True)
                .encode(x="Time:T", y=f"{col}:Q", color=alt.value(color))
                .properties(width=500, height=200, title=f"{label} - {title}")
            )
            st.altair_chart(chart, width="stretch")

# -----------------------------
# Load Index Tables
# -----------------------------
idx_tables = ["50","BANK","IT","PHARMA","METAL","OIL_GAS","TOTAL_MARKET"]
idx_path = os.path.join(BASE_DIR_db, 'allindices.db')

dfs = {tab: load_sql(idx_path, tab, f"SELECT * FROM '{tab}' WHERE Date='{TODAY}' ORDER BY Time DESC") for tab in idx_tables}
index_dataframes = {name: valuechange(dfs[tab]) for name, tab in zip(
    ["NIFTY 50","BANK","IT","PHARMA","METAL","OIL & GAS","TOTAL MARKET"], idx_tables)}

# -----------------------------
# Load Turnover Tables
# -----------------------------
tables = {
    'cm_total': ['Date','Time','pchg','Valchg','Volchg','Chgavg','Var%','Adv','Dec','Tavgchg%',
                 'Trdnochg','Orderchg_lac','averageTrade','Valchg%','Volchg%','Orderchg%','Trdnochg%','Totavg'],
    'fno_total': ['Date','Time','Valchg','Volchg','Chgavg','Var%','Adv','Dec','Tavgchg%',
                  'oival_lac','Trdnochg','Orderchg_lac','averageTrade','Ttrd','Unchg',
                  'Valchg%','Volchg%','Orderchg%','Trdnochg%','Totavg'],
    'grand_total': ['Date','Time','Valchg','Volchg','Chgavg','Var%','Adv','Dec','Tavgchg%',
                    'oival_lac','Trdnochg','averageTrade','noOfOrders','Ttrd','Unchg',
                    'Valchg%','Volchg%','Orderchg_lac','Orderchg%','Trdnochg%','Totavg']
}
db_path = os.path.join(BASE_DIR_db, "allturnover.db")

results = {t: diffprocess(load_sql(db_path, t, f"SELECT * FROM '{t}' WHERE Date='{TODAY}' ORDER BY Time DESC"))[cols]
           for t, cols in tables.items()}
turnover_dataframes = {"CM": results['cm_total'], "FNO": results['fno_total'], "GT": results['grand_total']}

# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(page_title="Indices & Turnover Dashboard", layout="wide")
st.title("📊 Indices & Turnover Change Dashboard")

# Sidebar selectors
selected_index = st.sidebar.selectbox("Select an Index:", list(index_dataframes.keys()))
selected_turnover = st.sidebar.selectbox("Select Turnover Table:", list(turnover_dataframes.keys()))

# Shared chart specs for both index and turnover
COMMON_CHART_SPECS = [
    ("Valchg", "blue", "Valchg (cr)"),
    ("Volchg", "green", "Volchg (lac)"),
    ("pchg", "orange", "% Change"),   # will be skipped if not present
    ("Chgavg", "purple", "Change Avg"),
    ("Totavg", "orange", "Total Avg"),
    ("Adv", "blue", "Advance"),
    ("Dec", "red", "Decline"),
]

# -----------------------------
# Index Section
# -----------------------------
st.subheader(f"{selected_index} DataFrame")
st.dataframe(index_dataframes[selected_index].head(50))

# Parse time with hh:mm:ss for index tables
plot_df = parse_time(index_dataframes[selected_index].copy(), "%H:%M:%S")

# Plot charts for index
plot_charts(plot_df, selected_index, COMMON_CHART_SPECS)

# -----------------------------
# Turnover Section
# -----------------------------
st.subheader(f"{selected_turnover} Turnover DataFrame")
st.dataframe(turnover_dataframes[selected_turnover].head(50))

# Parse time with hh:mm for turnover tables
plot_turnover_df = parse_time(turnover_dataframes[selected_turnover].copy(), "%H:%M")

# Plot charts for turnover
plot_charts(plot_turnover_df, selected_turnover, COMMON_CHART_SPECS)